# 对话框 配置文件描述
header: |-
  RsNPC - файл конфигурации диалогов
  Внимание! Перед редактированием убедитесь, что вы освоили синтаксис YAML!
footer: |-
  Вы достигли конца конфигурационного файла

defaultPage: "Страница, открываемая по умолчанию (укажите ключ из списка pages)"
pages: |-
  Формат страницы:
  - key: "1" # уникальный ключ страницы
    title: "Пример диалога" # заголовок страницы
    content: "Это демонстрационный диалог" # содержимое страницы
    sound: # звуковые эффекты при открытии
      enable: false
      identifier: "random.levelup"
    buttons: # кнопки
      - text: "закрыть" # отображаемое имя кнопки
        action: "close" # оставьте пустым для закрытия диалога
        cmd: # выполняемые команды
          - "me hello" # выполняется с правами игрока
          - "say hello @p&op" # выполняется с правами OP
          - "tell @p это тестовая команда&con" # выполняется консолью
        sound: # звук при нажатии кнопки
          enable: false
          identifier: "random.levelup"
      - text: "следующая страница" # отображаемое имя кнопки
        go: "2" # переход на другую страницу (укажите ключ страницы)
    close: # действие при закрытии диалога
      go: "4" # переход на указанную страницу (если не указано - остаётся текущая)