# NPC 配置文件描述
header: |-
  RsNPC - файл конфигурации NPC
  Внимание! Убедитесь, что вы понимаете синтаксис YAML перед редактированием!
footer: |-
  Вы достигли конца конфигурационного файла

ConfigVersion: |-
  Версия конфигурационного файла
  ВНИМАНИЕ! Не изменяйте эту настройку, если не уверены в своих действиях!

name: "Отображаемое имя NPC (над головой)"
nameTagAlwaysVisible: |-
  Видимость имени NPC:
  true - всегда видно
  false - видно только при наведении на NPC
坐标: "Координаты NPC"
手持: "ID предмета в руке (например 267:0), оставьте пустым для скрытия"
头部: "ID шлема (например 298:0), оставьте пустым для скрытия"
胸部: "ID нагрудника (например 299:0), оставьте пустым для скрытия"
腿部: "ID поножей (например 300:0), оставьте пустым для скрытия"
脚部: "ID ботинок (например 301:0), оставьте пустым для скрытия"
皮肤: "Используемый скин"
实体NetworkId: |-
  Network ID сущности для пакетов:
  Список ID: https://minecraft.fandom.com/wiki/Java_Edition_data_values/Pre-flattening/Entity_IDs
  По умолчанию: -1 (использует фейкового игрока)
实体大小: "Размер сущности"
看向玩家: "Следить ли за игроком взглядом"

表情动作.启用: "Включить эмоции NPC"
表情动作.表情ID: |-
  Список ID эмоций: https://github.com/lt-name/GetEmoteID/blob/master/README.md
  Формат (список):
   - "ID1"
   - "ID2"
表情动作.间隔: "Интервал между эмоциями (в секундах)"

允许抛射物触发: "Реагировать на снаряды (стрелы, снежки и т.д.)"

点击执行指令: |-
  Команды при клике на NPC (список):
  Формат:
   - "Команда1&Права"
   - "Команда2&Права"
  Права:
  &con - выполнение от имени консоли
  &op - выполнение с правами OP
  Пример:
   - "give @p 260 1&con"
   - "say @p hello&con"

发送消息: |-
  Сообщения при клике (список):
  Формат:
   - "Сообщение1"
   - "Сообщение2"
  Пример:
   - "%npcName%: @p Привет"
   - "Держи яблоко!"

基础移动速度: "Базовая скорость передвижения"
route: "Список точек маршрута (используйте команды для добавления)"
启用辅助寻路: |-
  Умный поиск пути:
  Включено - NPC обходит препятствия (рекомендуется при сложном рельефе)
  Выключено - NPC движется напрямую (экономит ресурсы на ровной местности)

旋转: |-
  Угол поворота NPC (отрицательное значение для обратного направления)
  Используется для поворота скинов
  Включая эту настройку, автоматически отключает движение NPC

对话框.启用: "Включить диалоговое окно"
对话框.页面: "Имя файла конфигурации диалога"

CustomEntity: |-
  Настройки пользовательских сущностей
  ВНИМАНИЕ! Требуется текстурпак!
  ВНИМАНИЕ! Игроки должны перезайти для отображения изменений!
CustomEntity.enable: "Включить пользовательскую сущность"
CustomEntity.identifier: "Идентификатор сущности (из ресурспака)"
CustomEntity.skinId: "ID варианта скина (обычно 0)"

CustomCollisionSize: |-
  Пользовательский размер коллизии
  Полезно для нестандартных форм скинов
  Позволяет лучше взаимодействовать с NPC
CustomCollisionSize.enable: "Включить кастомный размер коллизии"

