name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.2.2-SNAPSHOT"
api:
  - "1.0.9"
  - "1.0.11"
authors: ["若水", "LT_Name"]
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

permissions:
  RsNPC.admin:
    default: op
    description: "RsNPC插件主命令"