name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.4.2"
api:
  - "1.0.9"
  - "1.0.11"
authors: ["若水", "LT_Name"]
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

permissions:
  RsNPC.admin:
    default: op
    description: "RsNPC插件主命令"
  RsNPC.create:
    default: op
    description: "创建npc的命令"
  RsNPC.delete:
    default: op
    description: "删除npc的命令"
  RsNPC.reload:
    default: op
    description: "重载NPC配置文件的命令"
  RsNPC.addroute:
    default: op
    description: "添加npc移动路径的命令"