name: RsNPCX
main: com.smallaswater.npc.RsNpcX
version: "1.8.9-SNAPSHOT"
api:
  - "1.0.9"
  - "1.0.11"
authors: ["若水", "LT_Name"]
load: POSTWORLD

permissions:
  RsNPCX.npc:
    default: op
    description: "RSNPCX插件主命令"