name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.5.2-NKX"
api:
  - "1.0.9"
  - "1.0.11"
authors: ["若水", "LT_Name"]
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

permissions:
  RsNPC.admin:
    default: op
    description: "RsNPC 插件主命令"
  RsNPC.admin.create:
    default: op
    description: "RsNPC 创建NPC命令"
  RsNPC.admin.delete:
    default: op
    description: "RsNPC 删除NPC命令"
  RsNPC.admin.reload:
    default: op
    description: "RsNPC 重载配置文件命令"
  RsNPC.admin.addroute:
    default: op
    description: "RsNPC 添加NPC移动路径命令"