name: RsNPCX
main: com.smallaswater.npc.RsNpcX
version: "1.6.0"
api:
  - "1.0.9"
  - "1.0.11"
authors: ["若水", "LT_Name"]
load: POSTWORLD
commands:
  rsnpcx:
    description: "RSNPCX插件主命令"
    usage: "/rnpcx help"
    permission: RsNPCX.npc
permissions:
  RsNPCX.npc:
    default: op
    description: "RSNPCX插件主命令"